import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { payrollApi } from '../api/payroll';
import DataTable from '../components/DataTable';
import Badge from '../components/Badge';
import { IconRupee, IconPlus } from '../components/icons.jsx';

const STATUS_TONE = { draft: 'amber', finalized: 'green' };
const MONTH_NAMES = Array.from({ length: 12 }, (_, i) => new Date(2000, i, 1).toLocaleDateString('en-IN', { month: 'long' }));

export default function PayrollRuns() {
  const { token } = useAuth();
  const [runs, setRuns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [month, setMonth] = useState(new Date().getMonth() + 1);
  const [year, setYear] = useState(new Date().getFullYear());
  const [generating, setGenerating] = useState(false);

  function load() {
    setLoading(true);
    payrollApi.listRuns(token).then(setRuns).catch((err) => setError(err.message)).finally(() => setLoading(false));
  }

  useEffect(load, [token]);

  async function handleGenerate(e) {
    e.preventDefault();
    setError('');
    setGenerating(true);
    try {
      await payrollApi.generateRun(token, month, year);
      load();
    } catch (err) {
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  }

  const columns = [
    { key: 'period', label: 'Period', render: (r) => <span className="font-medium text-gray-800">{MONTH_NAMES[r.month - 1]} {r.year}</span> },
    { key: 'status', label: 'Status', render: (r) => <Badge tone={STATUS_TONE[r.status] || 'gray'} dot>{r.status}</Badge> },
    { key: 'generated_by_name', label: 'Generated By', render: (r) => r.generated_by_name || '—' },
  ];

  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <div className="page-header-icon">
          <IconRupee style={{ width: 22, height: 22 }} />
        </div>
        <div>
          <h1 className="page-title">Payroll Runs</h1>
          <p className="text-sm text-gray-400">{runs.length} runs on record</p>
        </div>
      </div>

      <div className="card p-4 mb-5">
        <form onSubmit={handleGenerate} className="flex items-end gap-3 flex-wrap">
          <div>
            <label className="field-label text-xs">Month</label>
            <select value={month} onChange={(e) => setMonth(Number(e.target.value))} className="input-field">
              {MONTH_NAMES.map((m, i) => <option key={m} value={i + 1}>{m}</option>)}
            </select>
          </div>
          <div>
            <label className="field-label text-xs">Year</label>
            <input type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} className="input-field w-24" />
          </div>
          <button type="submit" className="btn-primary" disabled={generating}>
            <IconPlus style={{ width: 16, height: 16 }} /> {generating ? 'Generating...' : 'Generate / Recompute'}
          </button>
        </form>
        <p className="text-xs text-gray-400 mt-2">Generating a draft that already exists recomputes it from current attendance and salaries.</p>
      </div>

      {error && <div className="alert-error mb-4">{error}</div>}
      {loading ? <div className="text-gray-500">Loading payroll runs...</div> : (
        <DataTable columns={columns} rows={runs} emptyMessage="No payroll runs yet." renderActions={(r) => (
          <Link to={`/payroll/${r.id}`} className="btn-link">View</Link>
        )} />
      )}
    </div>
  );
}
